#=================================
#        Server ??
#=================================
server:
  port: 8080
  error:
    include-exception: false
    whitelabel:
      enabled: true

#=================================
#        DB ??
#=================================
    datasource:
      username: root
      password: yeonji106
      db_schema: study
      connect-timeout: 3
      read-timeout: 3
      write-timeout: 3

      jdbc-url:
      jdbc:mariadb://127.0.0.1:3306/study?autoReconnect=true&serverTimezone=Asia/Seoul&useSSL=false&allowMultiQueries=true&useUnicode=ture&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&&allowMultiQueries=true

#spring.mvc.pathmatch.matching-strategy=ant_path_matcher

